import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RootLayoutComp from '@/layouts/RootLayoutComp'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ImGen',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <RootLayoutComp>{children}</RootLayoutComp>
      </body>
    </html>
  )
}
